### ISSUE TITLE
vendor master branch

### ISSUE THREAD

**Issue by kibal** [subgraph/subgraph_metaproxy#2]
Please vendor the master branch and the debian branch should be ready to build with git-buildpackage. It may require additional minimal changes to the debian branch.

**Comment by mckinney-subgraph** [comment]
Correct me if I am wrong but I don't think we need to vendor anything. `golang.org/x/net/proxy` is the only external import and it is already available in Debian (see [https://packages.debian.org/stretch/all/golang-golang-x-net-dev]). I don't know how this works in practice but I think this complies with Debian golang policy. Any thoughts @xSmurf?

**Comment by xSmurf** [comment]
Can't comment really, either way seems fine to me.

**Comment by kibal** [comment]
We can use ```golang-golang-x-net-dev``` as well. Tag v0.5.1 on master branch and 7869039 on debian branch now produce a working debian package with gbp.
